version: '3.8'
services:
  minio:
    image: 'minio/minio'
    container_name: 'MinIO_Container'
    ports:
      - "7000:9000"
      - "7001:9001"
    environment:
      MINIO_ROOT_USER: Maxim
      MINIO_ROOT_PASSWORD: 1337R1337R
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minio_set
    restart: unless-stopped

volumes:
  minio_data:

networks:
  minio_set: